---
- name: Check if dotfiles exists
  stat: path=~/{{ item }}
  with_items: "{{ dotfiles_name }}"
  register: dotfiles

- name: Add symbolic link to dotfiles
  shell: ln -s ~/osx-provisioner/dotfiles/{{ item }} ~/{{ item }}
  with_items: "{{ dotfiles.results }}"
  when: not item.stat.exists
