---
- name: Add symbolic link to dotfiles
  shell: ln -s ~/osx-provisioner/dotfiles/{{ item }} ~/{{ item }}
  with_items: "{{ dotfiles_name }}"

- name: molokai location config file directory
  file: path=~/.vim/colors state=directory owner=root group=root mode=0755

- name: install molokai
  git: repo=https://github.com/tomasr/molokai.git dest=~/.vim/colors/

- name: copy molokai.vim
  copy: src=~/.vim/colors/molokai/colors/molokai.vim dest=~/.vim/colors/
